### ISSUE TITLE
Meta percentages should be smarter.

### ISSUE THREAD

**Issue by lewisgoddard** [eustasy/gorgon#8]
Rather than community just showing 8% for 34/38 we should calculate based on each work item within it. That would look like a lot more reasonable result. Requires changes to all API points, and 

- [x] repositories-community
- [x] repositories-labels
- [x] repositories-with-unreleased-commits
- [x] repositories-without-normalized-builds
- [x] issues-closed-and-unassigned
- [x] issues-without-priority

We should consider adding work items as an alternative to repositories affected to the dashboard / meta table.

Partially blocked by eustasy/gorgon#7
